# Generated by roxytest: Do not edit by hand!

# File R/scoring.R: @testexamples

test_that("Function gcap.runScoring() @ L23", {
  data("ec")
  ec2 <- ec
  ec2$pred <- gcap.runPrediction(ec)
  score <- gcap.runScoring(ec2)
  score
  expect_equal(nrow(score), 1L)
})
