# Generated by roxytest: Do not edit by hand!

# File R/cn_components.R: @testexamples

test_that("Function gcap.extractComponents() @ L28", {
  
  set.seed(2021)
  x <- c(rnorm(10, 0), rnorm(50, 1), rnorm(20, 4), rnorm(5, 10))
  y <- gcap.extractComponents(x, max_comp = 5)
  y
  expect_equal(nrow(y$params), 3)
})

