# Generated by roxytest: Do not edit by hand!

# File R/scoring.R: @testexamples

test_that("Function gcap.runScoring() @ L22", {
  
  data("ec")
  ec2 <- ec
  ec2$prob <- gcap.runPrediction(ec)
  score <- gcap.runScoring(ec2)
  score
  expect_equal(length(score), 3L)
})

