# Generated by roxytest: Do not edit by hand!

# File R/plotProfile.R: @testexamples

test_that("Function gcap.plotProfile() @ L70", {
  
  
  if (require("ComplexHeatmap") && require("IDConverter")) {
    data("ascn")
    data <- ascn
  
    # Create fake data
    set.seed(1234)
    data$sample <- sample(LETTERS[1:10], nrow(data), replace = TRUE)
    rv <- gcap.ASCNworkflow(data, outdir = tempdir(), model = "XGB11")
  
    gcap.plotProfile(rv, samples = c("B", "A", "C"))
  
    rv$convertGeneID()
    ht <- gcap.plotProfile(rv,
      samples = c("B", "A", "C", "D", "F"),
      genes = unique(rv$data$gene_id)[1:10],
      top_annotation = ComplexHeatmap::HeatmapAnnotation(
        cbar = ComplexHeatmap::anno_oncoprint_barplot(),
        foo1 = c("g1", "g1", "g2", "g2", "g3"),
        bar1 = ComplexHeatmap::anno_points(1:5)
      )
    )
    ht
    ComplexHeatmap::draw(ht, merge_legends = TRUE)
  
    #----------------
    # Plot KM curve
    #----------------
    surv_data <- data.frame(
      sample = rv$sample_summary$sample,
      time = 3000 * abs(rnorm(nrow(rv$sample_summary))),
      status = sample(c(0, 1), nrow(rv$sample_summary), replace = TRUE)
    )
    surv_data
    p <- gcap.plotKMcurve(rv, surv_data)
    p
  
    p2 <- gcap.plotKMcurve(rv, surv_data, genes = "MYC")
    p2
  }
  
  expect_is(ht, "Heatmap")
  expect_is(p, "ggsurvplot")
  if (!is.null(p2)) {
    expect_is(p2, "ggsurvplot")
  }
})

