# Generated by roxytest: Do not edit by hand!

# File R/ASCNworkflow.R: @testexamples

test_that("Function gcap.ASCNworkflow() @ L42", {
  
  data("ascn")
  data <- ascn
  rv <- gcap.ASCNworkflow(data, outdir = tempdir())
  data$purity <- 1
  rv2 <- gcap.ASCNworkflow(data, outdir = tempdir())
  data$age <- 60
  data$gender <- "XY"
  rv3 <- gcap.ASCNworkflow(data, outdir = tempdir())
  expect_equal(rv, rv2)
  expect_equal(ncol(rv3$by_gene), 35L)
})

