# Generated by roxytest: Do not edit by hand!

# File R/ASCNworkflow.R: @testexamples

test_that("Function gcap.ASCNworkflow() @ L52", {
  
  data("ascn")
  data <- ascn
  rv <- gcap.ASCNworkflow(data, outdir = tempdir(), model = "XGB11")
  data$purity <- 1
  rv2 <- gcap.ASCNworkflow(data, outdir = tempdir(), model = "XGB11")
  data$age <- 60
  data$gender <- "XY"
  rv3 <- gcap.ASCNworkflow(data, outdir = tempdir(), model = "XGB32")
  # If you want to use 'XGB54', you should include 'type' column
  data$type <- "LUAD"
  rv4 <- gcap.ASCNworkflow(data, outdir = tempdir(), model = "XGB54")
  # If you only have total integer copy number
  data$minor_cn <- NA
  rv5 <- gcap.ASCNworkflow(data, outdir = tempdir(), model = "XGB11")
  expect_equal(rv, rv2)
  expect_equal(length(rv3), 2L)
  expect_equal(length(rv4), 2L)
  expect_equal(length(rv5), 2L)
  expect_error(gcap.ASCNworkflow(data, outdir = tempdir()))
})

