# Generated by roxytest: Do not edit by hand!

# File R/auc.R: @testexamples

test_that("Function get_auc() @ L19", {
  
  set.seed(2021)
  auc <- get_auc(sample(1:10, 10), c(rep(0, 5), rep(1, 5)))
  auc
  expect_equal(length(auc), 3)
  expect_s3_class(auc, "PRROC")
})

