# Generated by roxytest: Do not edit by hand!

# File R/scoring2.R: @testexamples

test_that("Function gcap.runScoring2() @ L23", {
  
  data("ec")
  ec2 <- ec
  ec2$prob <- gcap.runPrediction(ec)
  score <- gcap.runScoring(ec2)
  score
  expect_equal(length(score), 2L)
})

