# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

vec_shift <- function(arr) {
    .Call(`_gcap_vec_shift`, arr)
}

conv_binomial <- function(p) {
    .Call(`_gcap_conv_binomial`, p)
}

